version: "3"

services:
  cdn:
    image: "ghcr.io/jungvengers/sunrinsecurity-cdn-v1:master"
    env_file:
      - .env
    environment:
      - PORT=3000
    volumes:
      - upload:/app/upload
    ports:
      - 4000:3000
    extra_hosts:
      - host.docker.internal:host-gateway

  frontend:
    build: ./logcon-frontend-main
    env_file:
      - ./logcon-frontend-main/.env
    ports:
      - "3001:3000"

  db:
    image: mysql:8.0.3
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
    env_file: .env
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  backend:
    build: ./logcon-backend-main
    restart: always
    ports:
      - "3002:3000"
    env_file:
      - ./logcon-backend-main/src/env/production.env
    depends_on:
      - db

volumes:
  upload:
